version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: immobilier-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: immobilier_db
    networks:
      - immobilier-network

  api:
    build: .
    container_name: immobilier-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/immobilier_db
      JWT_SECRET: votre_clé_secrète_très_sécurisée_min_32_caractères!@#$%
    networks:
      - immobilier-network
    restart: on-failure

networks:
  immobilier-network:
    driver: bridge

volumes:
  mongo-data:
